language: python
cache: pip
services: mongodb
branches:
  only:
    - master
python:
  - "2.7"
  # Disabled testing with Python 3 because some libraries don't support it.
  # - "3.2"
  # - "3.3"
  # - "3.4"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
      # Using system scipy because it's too slow to compile for travis.
      - python-scipy
      - python-numpy
before_install:
    - export PIP_USE_MIRRORS=true
    # Linear algebra (Scipy deps).
    # - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran python-dev
    # Start X for selenium tests.
    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - sleep 3
install:
  # Upgrade pip.
  - pip install --upgrade pip
  # Deps.
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install coveralls
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
notifications:
  irc:
    channels: "irc.freenode.org#ghiro"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
sudo: false